model:
  name: "meta-llama/Llama-3.2-3B-Instruct" # Requires Hugging Face authentication
  device: "cuda" # Will fall back to "cpu" if CUDA not available

compression:
  type: svd # or 'tucker'
  rank: 32
  ranks: [32, 32, 32]

dataset:
  name: "wikitext"
  config: "wikitext-2-raw-v1"
  split: "train"
  batch_size: 4
  max_length: 128
